# Generated by Django 2.2.4 on 2019-10-09 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='airline',
            name='airlinecode',
            field=models.CharField(default='PK', max_length=5),
            preserve_default=False,
        ),
    ]
