# Generated by Django 2.2.4 on 2019-10-11 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20191010_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinstallment',
            name='description',
            field=models.TextField(default='description'),
            preserve_default=False,
        ),
    ]
