# Generated by Django 2.2.4 on 2019-10-02 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TravelAgency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tname', models.CharField(max_length=50, null=True, unique=True)),
                ('contact', models.IntegerField(null=True, unique=True)),
                ('propname', models.CharField(max_length=50, null=True, unique=True)),
                ('procontact', models.IntegerField(null=True, unique=True)),
                ('countername', models.CharField(max_length=50, null=True, unique=True)),
                ('countercontact', models.IntegerField(null=True, unique=True)),
                ('accountantname', models.CharField(max_length=50, null=True, unique=True)),
                ('accountantcontact', models.IntegerField(null=True, unique=True)),
                ('description', models.TextField()),
            ],
        ),
    ]
